name       : python-starlette
version    : 0.20.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/s/starlette/starlette-0.20.4.tar.gz : 42fcf3122f998fefce3e2c5ad7e5edbf0f02cf685d646a83a08d404726af5084
homepage   : https://www.starlette.io/
license    : BSC-3-Clause
component  : programming.python
summary    : The little ASGI framework that shines
description: |
    Starlette is a lightweight ASGI framework/toolkit, which is ideal for building async web services in Python.
rundeps    :
    - python-anyio
build      : |
    %python3_setup
install    : |
    %python3_install
