name       : python-starlette
version    : 0.31.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/s/starlette/starlette-0.31.0.tar.gz : 7df0a3d8fa2c027d641506204ef69239d19bf9406ad2e77b319926e476ac3042
homepage   : https://github.com/encode/starlette
license    : BSC-3-Clause
component  : programming.python
summary    : The little ASGI framework that shines
description: |
    Starlette is a lightweight ASGI framework/toolkit, which is ideal for building async web services in Python.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-anyio
build      : |
    %python3_setup
install    : |
    %python3_install
