name       : python-starlette
version    : 0.21.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/s/starlette/starlette-0.21.0.tar.gz : b1b52305ee8f7cfc48cde383496f7c11ab897cd7112b33d998b1317dc8ef9027
homepage   : https://github.com/encode/starlette
license    : BSC-3-Clause
component  : programming.python
summary    : The little ASGI framework that shines
description: |
    Starlette is a lightweight ASGI framework/toolkit, which is ideal for building async web services in Python.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-anyio
build      : |
    %python3_setup
install    : |
    %python3_install
